/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package db.project;

import javafx.stage.Stage;

public class App extends javafx.application.Application {

    @Override
    public void start(Stage primaryStage) throws Exception {
        // TODO Auto-generated method stub
        
    }

}
