package db.project.model;

public enum OPERATION_OUTCOME {
	
	MISSING_ARGUMENTS,
	OVERLAPPING,
	WRONG_INSERTION,
	CAPACITY_REACHED,
	MISSING_PERSON,
	EXIT_DATE_PRESENT,
	EXIT_DATE_MISSING,
	PENDING_CURES,
	PENDING_APPOINTMENTS,
	FAILURE,
	SUCCESS,
	REPORT_INVOLVMENT;

}
